# Generated by Django 3.1.5 on 2021-03-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('collegeid', models.CharField(max_length=10)),
                ('registration_number', models.CharField(max_length=20)),
                ('current_year', models.IntegerField(max_length=1)),
                ('department', models.CharField(max_length=15)),
            ],
        ),
    ]
