# Generated by Django 3.1.5 on 2021-03-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeId', models.CharField(max_length=8, null=True)),
                ('voterName', models.CharField(max_length=30, null=True)),
                ('voterDepartment', models.CharField(max_length=20, null=True)),
                ('academic_year', models.CharField(max_length=1, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('voting_status', models.CharField(choices=[('Pending', 'Pending'), ('Voted', 'Voted')], max_length=10, null=True)),
            ],
        ),
    ]
