# Generated by Django 3.1.5 on 2021-03-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=8)),
                ('voter_name', models.CharField(max_length=30)),
                ('voter_department', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=1)),
                ('collegeid', models.CharField(max_length=10)),
            ],
        ),
    ]
