# Generated by Django 3.1.5 on 2021-03-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='date_of_birth',
        ),
    ]
