# Generated by Django 3.1.5 on 2021-03-09 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votingpanel', '0002_remove_voter_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='voter',
            name='collegeId',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateName', models.CharField(max_length=50, null=True)),
                ('total_vote', models.IntegerField(default=0, editable=False)),
                ('email', models.CharField(max_length=40, null=True)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='votingpanel.position')),
            ],
        ),
    ]
