# Generated by Django 3.1.5 on 2021-03-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingpanel', '0002_remove_voter_collegeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='voter_id',
            new_name='college_id',
        ),
    ]
