# Generated by Django 3.1.5 on 2021-03-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingpanel', '0003_auto_20210302_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate_name', models.CharField(max_length=20)),
                ('Candidate_department', models.CharField(max_length=20)),
                ('Candidate_party_name', models.CharField(max_length=20)),
                ('Candidate_work', models.CharField(max_length=20)),
            ],
        ),
    ]
