# Generated by Django 3.1.5 on 2021-03-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingpanel', '0004_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
