# Generated by Django 3.1.5 on 2021-03-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingpanel', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voterId', models.IntegerField()),
                ('candidateId', models.IntegerField()),
                ('positionId', models.IntegerField()),
            ],
        ),
    ]
