# Generated by Django 3.1.5 on 2021-03-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingpanel', '0005_voter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
