# Generated by Django 3.1.5 on 2021-03-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingpanel', '0005_countvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countvote',
            name='candidateId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='countvote',
            name='positionId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='countvote',
            name='voterId',
            field=models.IntegerField(null=True),
        ),
    ]
