# Generated by Django 3.1.5 on 2021-03-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingpanel', '0006_auto_20210312_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='total_vote',
        ),
    ]
