# Generated by Django 3.1.5 on 2021-03-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingpanel', '0006_voter_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Candidate_department',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Candidate_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Candidate_party_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Candidate_work',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='academic_year',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='college_id',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_department',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
