# Generated by Django 3.1.5 on 2021-03-02 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votingpanel', '0008_voter_voting_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votingpanel.candidate')),
                ('Voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votingpanel.voter')),
            ],
        ),
    ]
