# Generated by Django 3.1.5 on 2021-03-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingpanel', '0009_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
