# Generated by Django 3.1.5 on 2021-03-08 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votingpanel', '0010_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Candidate',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Voter',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Candidate_department',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Candidate_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Candidate_party_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Candidate_work',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='college_id',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='voter_department',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='voter_name',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='voting_status',
        ),
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_vote',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='academicyear',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='branch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='collegeid',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='faculty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.AddField(
            model_name='controlvote',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingpanel.position'),
        ),
        migrations.AddField(
            model_name='controlvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='votingpanel.position'),
        ),
    ]
